name = "gtkadaquoter"
description = ""
version = "0.1.0-dev"

authors = ["John Perry"]
maintainers = ["John Perry <devotus@yahoo.com>"]
maintainers-logins = ["johnperry-math"]
licenses = "MIT OR Apache-2.0"
website = ""
tags = []

executables = ["gtkadaquoter"]
[[depends-on]]
gtkada = "^23.0.0"

[[depends-on]]
gnatcoll = "^24.0.0"
